enableColors: true

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    dependencies:
      typescript: "*"
  gatsby-plugin-sass@*:
    dependencies:
      webpack: "*"
  gatsby-source-contentful@*:
    dependencies:
      react: "*"
      react-dom: "*"
  gatsby-theme-parent@*:
    dependencies:
      "@babel/core": "*"
      babel-plugin-styled-components: "*"
      gatsby-theme-child: "*"
      react-helmet: "*"
      react-is: "*"
      sass: "*"
      styled-components: "*"
  gatsby@*:
    dependencies:
      babel-eslint: "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"

pnpFallbackMode: all

progressBarStyle: hogsfather

yarnPath: .yarn/releases/yarn-2.4.2.cjs
